SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `xmpic`;
CREATE TABLE `xmpic` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `turl` varchar(120) CHARACTER SET utf8mb4 NOT NULL,
  `wurl` varchar(120) CHARACTER SET utf8mb4 NOT NULL,
  `size` varchar(10) NOT NULL,
  `title` varchar(10) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
